title: aross.se
name: aross.se
email: alex@aross.se
description: "Creative and ingenious developer who loves to play around with Swift and Ruby to make awesome web and iOS projects"
base_url: /
url: https://aross.se
# markdown: redcarpet
# highlighter: rouge
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'sass', 'watch', 'style.scss', 'Rakefile']
# paginate: 30
