name: aross.se
description: "Happy developer which loves to play around with Ruby, JavaScript and other stuff thats related to mobile and web development"

markdown: redcarpet
pygments: true
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'sass', 'watch', 'style.scss', 'Rakefile']
paginate: 30
